-- Deploy orizons:0090-add_country_table to pg

BEGIN;

DROP TABLE IF EXISTS country;

CREATE DOMAIN TEXT_CODE_COUNTRY AS TEXT CHECK(VALUE ~ '^[A-Z]{3}$');

CREATE TABLE IF NOT EXISTS "country"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"code" TEXT_CODE_COUNTRY UNIQUE NOT NULL,
"en_name" TEXT NOT NULL UNIQUE,
"fr_name" TEXT NOT NULL UNIQUE
);

INSERT INTO "country" ("code", "en_name", "fr_name") VALUES
('AFG', 'Afghanistan', 'Afghanistan'),
('ALB', 'Albania', 'Albanie'),
('ATA', 'Antarctica', 'Antarctique'),
('DZA', 'Algeria', 'Algérie'),
('ASM', 'American Samoa', 'Samoa Américaines'),
('AND', 'Andorra', 'Andorre'),
('AGO', 'Angola', 'Angola'),
('ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda'),
('AZE', 'Azerbaijan', 'Azerbaïdjan'),
('ARG', 'Argentina', 'Argentine'),
('AUS', 'Australia', 'Australie'),
('AUT', 'Austria', 'Autriche'),
('BHS', 'Bahamas', 'Bahamas'),
('BHR', 'Bahrain', 'Bahreïn'),
('BGD', 'Bangladesh', 'Bangladesh'),
('ARM', 'Armenia', 'Arménie'),
('BRB', 'Barbados', 'Barbade'),
('BEL', 'Belgium', 'Belgique'),
('BMU', 'Bermuda', 'Bermudes'),
('BTN', 'Bhutan', 'Bhoutan'),
('BOL', 'Bolivia', 'Bolivie'),
('BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'),
('BWA', 'Botswana', 'Botswana'),
('BVT', 'Bouvet Island', 'Île Bouvet'),
('BRA', 'Brazil', 'Brésil'),
('BLZ', 'Belize', 'Belize'),
('IOT', 'British Indian Ocean Territory', 'Territoire Britannique de l''Océan Indien'),
('SLB', 'Solomon Islands', 'Îles Salomon'),
('VGB', 'British Virgin Islands', 'Îles Vierges Britanniques'),
('BRN', 'Brunei Darussalam', 'Brunéi Darussalam'),
('BGR', 'Bulgaria', 'Bulgarie'),
('MMR', 'Myanmar', 'Myanmar'),
('BDI', 'Burundi', 'Burundi'),
('BLR', 'Belarus', 'Bélarus'),
('KHM', 'Cambodia', 'Cambodge'),
('CMR', 'Cameroon', 'Cameroun'),
('CAN', 'Canada', 'Canada'),
('CPV', 'Cape Verde', 'Cap-vert'),
('CYM', 'Cayman Islands', 'Îles Caïmanes'),
('CAF', 'Central African', 'République Centrafricaine'),
('LKA', 'Sri Lanka', 'Sri Lanka'),
('TCD', 'Chad', 'Tchad'),
('CHL', 'Chile', 'Chili'),
('CHN', 'China', 'Chine'),
('TWN', 'Taiwan', 'Taïwan'),
('CXR', 'Christmas Island', 'Île Christmas'),
('CCK', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)'),
('COL', 'Colombia', 'Colombie'),
('COM', 'Comoros', 'Comores'),
('MYT', 'Mayotte', 'Mayotte'),
('COG', 'Republic of the Congo', 'République du Congo'),
('COD', 'The Democratic Republic Of The Congo', 'République Démocratique du Congo'),
('COK', 'Cook Islands', 'Îles Cook'),
('CRI', 'Costa Rica', 'Costa Rica'),
('HRV', 'Croatia', 'Croatie'),
('CUB', 'Cuba', 'Cuba'),
('CYP', 'Cyprus', 'Chypre'),
('CZE', 'Czech Republic', 'République Tchèque'),
('BEN', 'Benin', 'Bénin'),
('DNK', 'Denmark', 'Danemark'),
('DMA', 'Dominica', 'Dominique'),
('DOM', 'Dominican Republic', 'République Dominicaine'),
('ECU', 'Ecuador', 'Équateur'),
('SLV', 'El Salvador', 'El Salvador'),
('GNQ', 'Equatorial Guinea', 'Guinée Équatoriale'),
('ETH', 'Ethiopia', 'Éthiopie'),
('ERI', 'Eritrea', 'Érythrée'),
('EST', 'Estonia', 'Estonie'),
('FRO', 'Faroe Islands', 'Îles Féroé'),
('FLK', 'Falkland Islands', 'Îles (malvinas) Falkland'),
('SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud'),
('FJI', 'Fiji', 'Fidji'),
('FIN', 'Finland', 'Finlande'),
('ALA', 'Åland Islands', 'Îles Åland'),
('FRA', 'France', 'France'),
('GUF', 'French Guiana', 'Guyane Française'),
('PYF', 'French Polynesia', 'Polynésie Française'),
('ATF', 'French Southern Territories', 'Terres Australes Françaises'),
('DJI', 'Djibouti', 'Djibouti'),
('GAB', 'Gabon', 'Gabon'),
('GEO', 'Georgia', 'Géorgie'),
('GMB', 'Gambia', 'Gambie'),
('PSE', 'Occupied Palestinian Territory', 'Territoire Palestinien Occupé'),
('DEU', 'Germany', 'Allemagne'),
('GHA', 'Ghana', 'Ghana'),
('GIB', 'Gibraltar', 'Gibraltar'),
('KIR', 'Kiribati', 'Kiribati'),
('GRC', 'Greece', 'Grèce'),
('GRL', 'Greenland', 'Groenland'),
('GRD', 'Grenada', 'Grenade'),
('GLP', 'Guadeloupe', 'Guadeloupe'),
('GUM', 'Guam', 'Guam'),
('GTM', 'Guatemala', 'Guatemala'),
('GIN', 'Guinea', 'Guinée'),
('GUY', 'Guyana', 'Guyana'),
('HTI', 'Haiti', 'Haïti'),
('HMD', 'Heard Island and McDonald Islands', 'Îles Heard et Mcdonald'),
('VAT', 'Vatican City State', 'Saint-Siège (état de la Cité du Vatican)'),
('HND', 'Honduras', 'Honduras'),
('HKG', 'Hong Kong', 'Hong-Kong'),
('HUN', 'Hungary', 'Hongrie'),
('ISL', 'Iceland', 'Islande'),
('IND', 'India', 'Inde'),
('IDN', 'Indonesia', 'Indonésie'),
('IRN', 'Islamic Republic of Iran', 'République Islamique d''Iran'),
('IRQ', 'Iraq', 'Iraq'),
('IRL', 'Ireland', 'Irlande'),
('ISR', 'Israel', 'Israël'),
('ITA', 'Italy', 'Italie'),
('CIV', 'Côte d''Ivoire', 'Côte d''Ivoire'),
('JAM', 'Jamaica', 'Jamaïque'),
('JPN', 'Japan', 'Japon'),
('KAZ', 'Kazakhstan', 'Kazakhstan'),
('JOR', 'Jordan', 'Jordanie'),
('KEN', 'Kenya', 'Kenya'),
('PRK', 'Democratic People''s Republic of Korea', 'République Populaire Démocratique de Corée'),
('KOR', 'Republic of Korea', 'République de Corée'),
('KWT', 'Kuwait', 'Koweït'),
('KGZ', 'Kyrgyzstan', 'Kirghizistan'),
('LAO', 'Lao People''s Democratic Republic', 'République Démocratique Populaire Lao'),
('LBN', 'Lebanon', 'Liban'),
('LSO', 'Lesotho', 'Lesotho'),
('LVA', 'Latvia', 'Lettonie'),
('LBR', 'Liberia', 'Libéria'),
('LBY', 'Libyan Arab Jamahiriya', 'Jamahiriya Arabe Libyenne'),
('LIE', 'Liechtenstein', 'Liechtenstein'),
('LTU', 'Lithuania', 'Lituanie'),
('LUX', 'Luxembourg', 'Luxembourg'),
('MAC', 'Macao', 'Macao'),
('MDG', 'Madagascar', 'Madagascar'),
('MWI', 'Malawi', 'Malawi'),
('MYS', 'Malaysia', 'Malaisie'),
('MDV', 'Maldives', 'Maldives'),
('MLI', 'Mali', 'Mali'),
('MLT', 'Malta', 'Malte'),
('MTQ', 'Martinique', 'Martinique'),
('MRT', 'Mauritania', 'Mauritanie'),
('MUS', 'Mauritius', 'Maurice'),
('MEX', 'Mexico', 'Mexique'),
('MCO', 'Monaco', 'Monaco'),
('MNG', 'Mongolia', 'Mongolie'),
('MDA', 'Republic of Moldova', 'République de Moldova'),
('MSR', 'Montserrat', 'Montserrat'),
('MAR', 'Morocco', 'Maroc'),
('MOZ', 'Mozambique', 'Mozambique'),
('OMN', 'Oman', 'Oman'),
('NAM', 'Namibia', 'Namibie'),
('NRU', 'Nauru', 'Nauru'),
('NPL', 'Nepal', 'Népal'),
('NLD', 'Netherlands', 'Pays-Bas'),
('ANT', 'Netherlands Antilles', 'Antilles Néerlandaises'),
('ABW', 'Aruba', 'Aruba'),
('NCL', 'New Caledonia', 'Nouvelle-Calédonie'),
('VUT', 'Vanuatu', 'Vanuatu'),
('NZL', 'New Zealand', 'Nouvelle-Zélande'),
('NIC', 'Nicaragua', 'Nicaragua'),
('NER', 'Niger', 'Niger'),
('NGA', 'Nigeria', 'Nigéria'),
('NIU', 'Niue', 'Niué'),
('NFK', 'Norfolk Island', 'Île Norfolk'),
('NOR', 'Norway', 'Norvège'),
('MNP', 'Northern Mariana Islands', 'Îles Mariannes du Nord'),
('UMI', 'United States Minor Outlying Islands', 'Îles Mineures Éloignées des États-Unis'),
('FSM', 'Federated States of Micronesia', 'États Fédérés de Micronésie'),
('MHL', 'Marshall Islands', 'Îles Marshall'),
('PLW', 'Palau', 'Palaos'),
('PAK', 'Pakistan', 'Pakistan'),
('PAN', 'Panama', 'Panama'),
('PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'),
('PRY', 'Paraguay', 'Paraguay'),
('PER', 'Peru', 'Pérou'),
('PHL', 'Philippines', 'Philippines'),
('PCN', 'Pitcairn', 'Pitcairn'),
('POL', 'Poland', 'Pologne'),
('PRT', 'Portugal', 'Portugal'),
('GNB', 'Guinea-Bissau', 'Guinée-Bissau'),
('TLS', 'Timor-Leste', 'Timor-Leste'),
('PRI', 'Puerto Rico', 'Porto Rico'),
('QAT', 'Qatar', 'Qatar'),
('REU', 'Réunion', 'Réunion'),
('ROU', 'Romania', 'Roumanie'),
('RUS', 'Russian Federation', 'Fédération de Russie'),
('RWA', 'Rwanda', 'Rwanda'),
('SHN', 'Saint Helena', 'Sainte-Hélène'),
('KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'),
('AIA', 'Anguilla', 'Anguilla'),
('LCA', 'Saint Lucia', 'Sainte-Lucie'),
('SPM', 'Saint-Pierre and Miquelon', 'Saint-Pierre-et-Miquelon'),
('VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les Grenadines'),
('SMR', 'San Marino', 'Saint-Marin'),
('STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe'),
('SAU', 'Saudi Arabia', 'Arabie Saoudite'),
('SEN', 'Senegal', 'Sénégal'),
('SYC', 'Seychelles', 'Seychelles'),
('SLE', 'Sierra Leone', 'Sierra Leone'),
('SGP', 'Singapore', 'Singapour'),
('SVK', 'Slovakia', 'Slovaquie'),
('VNM', 'Vietnam', 'Viet Nam'),
('SVN', 'Slovenia', 'Slovénie'),
('SOM', 'Somalia', 'Somalie'),
('ZAF', 'South Africa', 'Afrique du Sud'),
('ZWE', 'Zimbabwe', 'Zimbabwe'),
('ESP', 'Spain', 'Espagne'),
('ESH', 'Western Sahara', 'Sahara Occidental'),
('SDN', 'Sudan', 'Soudan'),
('SUR', 'Suriname', 'Suriname'),
('SJM', 'Svalbard and Jan Mayen', 'Svalbard etÎle Jan Mayen'),
('SWZ', 'Swaziland', 'Swaziland'),
('SWE', 'Sweden', 'Suède'),
('CHE', 'Switzerland', 'Suisse'),
('SYR', 'Syrian Arab Republic', 'République Arabe Syrienne'),
('TJK', 'Tajikistan', 'Tadjikistan'),
('THA', 'Thailand', 'Thaïlande'),
('TGO', 'Togo', 'Togo'),
('TKL', 'Tokelau', 'Tokelau'),
('TON', 'Tonga', 'Tonga'),
('TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago'),
('ARE', 'United Arab Emirates', 'Émirats Arabes Unis'),
('TUN', 'Tunisia', 'Tunisie'),
('TUR', 'Turkey', 'Turquie'),
('TKM', 'Turkmenistan', 'Turkménistan'),
('TCA', 'Turks and Caicos Islands', 'Îles Turks et Caïques'),
('TUV', 'Tuvalu', 'Tuvalu'),
('UGA', 'Uganda', 'Ouganda'),
('UKR', 'Ukraine', 'Ukraine'),
('MKD', 'The Former Yugoslav Republic of Macedonia', 'L''ex-République Yougoslave de Macédoine'),
('EGY', 'Egypt', 'Égypte'),
('GBR', 'United Kingdom', 'Royaume-Uni'),
('IMN', 'Isle of Man', 'Île de Man'),
('TZA', 'United Republic Of Tanzania', 'République-Unie de Tanzanie'),
('USA', 'United States', 'États-Unis'),
('VIR', 'U.S. Virgin Islands', 'Îles Vierges des États-Unis'),
('BFA', 'Burkina Faso', 'Burkina Faso'),
('URY', 'Uruguay', 'Uruguay'),
('UZB', 'Uzbekistan', 'Ouzbékistan'),
('VEN', 'Venezuela', 'Venezuela'),
('WLF', 'Wallis and Futuna', 'Wallis et Futuna'),
('WSM', 'Samoa', 'Samoa'),
('YEM', 'Yemen', 'Yémen'),
('SCG', 'Serbia and Montenegro', 'Serbie-et-Monténégro'),
('ZMB', 'Zambia', 'Zambie');

COMMIT;